export const recommendedRules = {
    // eslint
    "array-bracket-spacing": ["error", "never"],
    "brace-style": ["error", "stroustrup", { "allowSingleLine": true }],
    "curly": ["error", "all"],
    "indent": ["error", 4, { "SwitchCase": 1 }],
    "jsx-quotes": ["error", "prefer-double"],
    "keyword-spacing": ["error", {"before": true, "after": true}],
    "max-statements-per-line": ["error", { "max": 1 }],
    "no-fallthrough": "error",
    "no-global-assign": "error",
    "no-implicit-coercion": "error",
    "no-implicit-globals": "error",
    "no-loss-of-precision": "error",
    "no-negated-condition": "error",
    "no-nested-ternary": "error",
    "no-new-native-nonconstructor": "error",
    "no-obj-calls": "error",
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
    "no-prototype-builtins": "error",
    "no-setter-return": "error",
    "no-spaced-func": "error",
    "no-this-before-super": "error",
    "no-throw-literal": "error",
    "no-unsafe-finally": "error",
    "no-useless-catch": "error",
    "no-var": "error",
    "object-curly-spacing": ["error", "always"],
    "one-var": ["error", "never"],
    "operator-assignment": "error",
    "padding-line-between-statements": ["error",
        { "blankLine": "always", "prev": "*", "next": "for" },
        { "blankLine": "always", "prev": "for", "next": "*" },
        { "blankLine": "always", "prev": "*", "next": "return" },
        { "blankLine": "any", "prev": "block-like", "next": "return" },
    ],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "quotes": "error",
    "radix": ["error", "as-needed"],
    "require-atomic-updates": "error",
    "require-await": "error",
    "require-unicode-regexp": "error",
    "require-yield": "error",
    "rest-spread-spacing": ["error", "never"],
    "semi-spacing": ["error", {"before": false, "after": true}],
    "semi": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", {
        "anonymous": "never",
        "named": "never",
        "asyncArrow": "always"
    }],
    "space-in-parens": ["error", "never"],
    "space-infix-ops": "error",
    "spaced-comment": "error",
    "switch-colon-spacing": "error",
    "symbol-description": "error",
    "template-curly-spacing": "error",
    "template-tag-spacing": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "wrap-iife": ["error", "inside", {
        "functionPrototypeMethods": true
    }],
    "wrap-regex": "error",
    "yield-star-spacing": "error",
    "yoda": "error",
    
    // eslint-plugin-relics
    "relics/object-shorthand": "error",
    "relics/prefer-explicit-property-checks": "error",
    "relics/prefer-loose-equality": "error",
}